name: learn-github-actions
on:
  push:
    branches:
      - main

jobs:   
  build-and-test-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Run tests
      - name: Run Java Tests
        run: mvn test
        
  build-and-test-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  build-and-run-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-docker-image /.devcontainer/Dockerfile
      
      # Run Docker container
      - name: Run Docker container
        run: docker run my-docker-image
