name: learn-github-actions
on: [push]

jobs:
     
  build-and-test-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Run tests
      - name: Run Java Tests
        run: mvn test
        

  create-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact




